on: pull_request
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run PHP Unit
        run: vendor/bin/phpunit tests/

      - name: Run PhpInsights
        run: vendor/bin/phpinsights --no-interaction --min-quality=80 --min-complexity=75 --min-architecture=80 --min-style=90
